### ISSUE TITLE
Follow java coding standards for package name

### ISSUE THREAD

**Issue by DePaul-KenYu** [ManojPuttaswamy/DemonHub#8]
This issue for multiple package names, for exampleDemonHub should be demonHub, Categories should be categories, Payments should be payments, Reviews should be reviews.

**Comment by DePaul-KenYu** [comment]
It seems that code is not compiling because the github code has the uppercase package names but the code has lower case in the  java package name.

For example see Categories.java
![image](https://github.com/user-attachments/assets/80a20b91-7850-47ce-a37e-764a5c027c35)

![image](https://github.com/user-attachments/assets/44dee691-41bb-4866-be01-d61d3a9a191d)

**Comment by ManojPuttaswamy** [comment]
Hi Professor,

In my local repository I tried to change and push it. It’s changed in my
local repository but when I push to GitHub the folder name changes are not
visible. Can you guide me through this?



Thanks & Regards,
Manoj Puttaswamy

**Comment by DePaul-KenYu** [comment]
You will have to change the name of the folder first.

For example,

  1.
change it from Account to accounts
  2.
change accounts to account
  3.
check in

________________________________
From: ManojPuttaswamy ***@***.***>
Sent: Sunday, October 20, 2024 6:11 PM
To: ManojPuttaswamy/DemonHub ***@***.***>
Cc: Yu, Ken ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [ManojPuttaswamy/DemonHub] Follow java coding standards for package name (Issue #8)


Hi Professor,

In my local repository I tried to change and push it. It’s changed in my
local repository but when I push to GitHub the folder name changes are not
visible. Can you guide me through this?



Thanks & Regards,
Manoj Puttaswamy
